### ISSUE TITLE
Indexing error: unable to open database file

### ISSUE THREAD

**Issue by raphael10-collab** [ellenhp/airmail#27]
Downloaded planet-daily.osm.pbf : 

    root@k8s-eu-1-worker-4:~/airmail# ls -lah ./data
    total 80G
    drwxr-xr-x  2 root root 4.0K Sep  5 10:39 .
    drwxr-xr-x 10 root root 4.0K Sep  5 13:00 ..
    -rw-r--r--  1 root root  80G Sep  5 12:16 planet-daily.osm.pbf

Indexing gives this error message : 
    
    root@k8s-eu-1-worker-4:~/airmail# cargo run --bin indexer -- \
    > --wof-db /data/whosonfirst-data-admin-latest.spatial.db \
    > --index /data/index/ \
    > load-osm-pbf ./data/planet-daily.osm.pbf 
        Finished dev [unoptimized + debuginfo] target(s) in 10.37s
         Running `target/debug/indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db --index /data/index/ load-osm-pbf ./data/planet-daily.osm.pbf`
    Error: error returned from database: (code: 14) unable to open database file
    
    Caused by:
        (code: 14) unable to open database file

OS: Ubuntu 24.04
root@k8s-eu-1-worker-4:~/airmail# cargo --version
cargo 1.75.0

I tried also with `docker-compose` and with a much smaller .pbf file but got the same error:

    root@k8s-eu-1-worker-4:~/airmail/data# ls -lah
    total 81G
    drwxr-xr-x  3 root root 4.0K Sep  5 14:47 .
    drwxr-xr-x 10 root root 4.0K Sep  5 13:00 ..
    -rw-r--r--  1 root root 276M Sep  5 04:07 europe-germany-brandenburg.osm.pbf
    drwxr-xr-x  2 root root 4.0K Sep  5 14:46 index
    -rw-r--r--  1 root root  80G Sep  5 12:16 planet-daily.osm.pbf
    
    
    root@k8s-eu-1-worker-4:~/airmail# docker-compose run indexer \
    > indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db \
    > --index /data/index/ \
    > load-osm-pbf ./data/europe-germany-brandenburg.osm.pbf 
    WARN[0000] Found orphan containers ([airmail-indexer-run-51e81c1f4559]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
    Error: error returned from database: (code: 14) unable to open database file
    
    Caused by:
        (code: 14) unable to open database file

How to make it work?

**Comment by ellenhp** [comment]
Did you download the WhosOnFirst database? Should be covered in step 2 of the README instructions. If it's named something different from the default, you may need to edit the docker-compose.yaml here: https://github.com/ellenhp/airmail/blob/main/docker-compose.yaml#L24

**Comment by raphael10-collab** [comment]
Hi @ellenhp 

in `docker-compose.yaml` file the example file is `australia-latest.osm.pbf` : 

    root@k8s-eu-1-worker-4:~/airmail# cat docker-compose.yaml 
    name: airmail
    
    services:
      osmx:
        image: osmx:latest
        build:
          context: airmail_indexer
          dockerfile: ./Dockerfile.osmx
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: expand /data/australia-latest.osm.pbf /data/australia-latest.osm.osmx
    
      indexer:
        image: indexer:latest
        build:
          context: ./
          dockerfile: ./airmail_indexer/Dockerfile
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db --index /data/index/ --admin-cache /data/admin-cache load-osm-pbf /data/australia-oceania-latest.osm.pbf
    
      airmail:
        image: airmail:latest
        build:
          context: ./
          dockerfile: ./Dockerfile
        environment:
          AIRMAIL_BIND: "0.0.0.0:3000"
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        ports:
          - 3000:3000
        command: --index /data/index/


So, I downloaded in ./data folder https://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf  : 

    root@k8s-eu-1-worker-4:~/airmail# ls -lah ./data
    total 729M
    drwxr-xr-x 3 root root 4.0K Sep  5 18:03 .
    drwxr-xr-x 9 root root 4.0K Sep  5 18:09 ..
    -rw-r--r-- 1 root root 729M Sep  3 01:23 australia-latest.osm.pbf


Building the images : 

    root@k8s-eu-1-worker-4:~/airmail# docker compose build
    [+] Building 2.0s (48/48) FINISHED                                                                                                                                                                                                                                                                 docker:default
     => [airmail internal] load build definition from Dockerfile                                                                                                                                                                                                                                                 0.0s
     => => transferring dockerfile: 600B                                                                                                                                                                                                                                                                         0.0s
     => [airmail internal] load .dockerignore                                                                                                                                                                                                                                                                    0.0s
     => => transferring context: 96B                                                                                                                                                                                                                                                                             0.0s
     => [airmail internal] load metadata for docker.io/library/fedora:39                                                                                                                                                                                                                                         1.4s
     => [airmail internal] load metadata for docker.io/library/rust:1.76                                                                                                                                                                                                                                         1.3s
     => [osmx internal] load build definition from Dockerfile.osmx                                                                                                                                                                                                                                               0.1s
     => => transferring dockerfile: 788B                                                                                                                                                                                                                                                                         0.0s
     => [osmx internal] load .dockerignore                                                                                                                                                                                                                                                                       0.1s
     => => transferring context: 2B                                                                                                                                                                                                                                                                              0.0s
     => [osmx internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                                                                                                                         1.2s
     => [indexer internal] load .dockerignore                                                                                                                                                                                                                                                                    0.1s
     => => transferring context: 96B                                                                                                                                                                                                                                                                             0.1s
     => [indexer internal] load build definition from Dockerfile                                                                                                                                                                                                                                                 0.1s
     => => transferring dockerfile: 464B                                                                                                                                                                                                                                                                         0.1s
     => [airmail  1/10] FROM docker.io/library/rust:1.76@sha256:d36f9d8a9a4c76da74c8d983d0d4cb146dd2d19bb9bd60b704cdcf70ef868d3a                                                                                                                                                                                 0.0s
     => [indexer internal] load build context                                                                                                                                                                                                                                                                    0.2s
     => => transferring context: 54.26kB                                                                                                                                                                                                                                                                         0.1s
     => [osmx builder 1/8] FROM docker.io/library/ubuntu:20.04@sha256:fa17826afb526a9fc7250e0fbcbfd18d03fe7a54849472f86879d8bf562c629e                                                                                                                                                                           0.0s
     => CACHED [osmx stage-1 2/4] RUN apt-get update && apt-get install -y     libexpat1     libssl1.1   && rm -rf /var/lib/apt/lists/*                                                                                                                                                                          0.0s
     => CACHED [osmx builder 2/8] RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y     cmake     clang     libbz2-dev     libz-dev     libexpat-dev     libssl-dev     git   && rm -rf /var/lib/apt/lists/*                                                                    0.0s
     => CACHED [osmx builder 3/8] WORKDIR /usr/src/                                                                                                                                                                                                                                                              0.0s
     => CACHED [osmx builder 4/8] RUN git clone --recurse-submodules https://github.com/protomaps/OSMExpress.git                                                                                                                                                                                                 0.0s
     => CACHED [osmx builder 5/8] WORKDIR /usr/src/OSMExpress                                                                                                                                                                                                                                                    0.0s
     => CACHED [osmx builder 6/8] RUN git checkout 24cdc6cca55f45b4019e2d490c2321c366ca3362                                                                                                                                                                                                                      0.0s
     => CACHED [osmx builder 7/8] RUN cmake -DCMAKE_BUILD_TYPE=Release .                                                                                                                                                                                                                                         0.0s
     => CACHED [osmx builder 8/8] RUN make -j$(nproc)                                                                                                                                                                                                                                                            0.0s
     => CACHED [osmx stage-1 3/4] COPY --from=builder /usr/src/OSMExpress/osmx /usr/local/bin/osmx                                                                                                                                                                                                               0.0s
     => CACHED [osmx stage-1 4/4] WORKDIR /var/osm                                                                                                                                                                                                                                                               0.0s
     => [osmx] exporting to image                                                                                                                                                                                                                                                                                0.1s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:c0f9596ad434039d629b7f078723ffa0ab352c0653635ac59e8b1a23dc7c3f0a                                                                                                                                                                                                                 0.1s
     => => naming to docker.io/library/osmx:latest                                                                                                                                                                                                                                                               0.0s
     => [airmail internal] load build context                                                                                                                                                                                                                                                                    0.3s
     => => transferring context: 54.26kB                                                                                                                                                                                                                                                                         0.1s
     => [airmail stage-1 1/3] FROM docker.io/library/fedora:39@sha256:86ba29d15976848f8b9f27d533156d6e43553678d0832bb8ebc95ff6c2331be6                                                                                                                                                                           0.0s
     => CACHED [indexer  2/10] RUN apt-get update && apt-get install -y libssl-dev capnproto clang pkg-config libzstd-dev libsqlite3-mod-spatialite && rm -rf /var/lib/apt/lists/*                                                                                                                               0.0s
     => CACHED [indexer  3/10] WORKDIR /usr/src/airmail                                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  4/10] COPY ./airmail ./airmail                                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  5/10] COPY ./airmail_indexer ./airmail_indexer                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  6/10] COPY ./airmail_service ./airmail_service                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  7/10] COPY ./Cargo.toml ./Cargo.toml                                                                                                                                                                                                                                                    0.0s
     => CACHED [indexer  8/10] COPY ./Cargo.lock ./Cargo.lock                                                                                                                                                                                                                                                    0.0s
     => CACHED [indexer  9/10] RUN cargo install --path ./airmail_indexer                                                                                                                                                                                                                                        0.0s
     => CACHED [indexer 10/10] WORKDIR /var/airmail                                                                                                                                                                                                                                                              0.0s
     => [indexer] exporting to image                                                                                                                                                                                                                                                                             0.1s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:0b6cda1f7402eed2ab9f920235ab2ea8f53861eca7a7b7e38f5c17fae0600b3c                                                                                                                                                                                                                 0.1s
     => => naming to docker.io/library/indexer:latest                                                                                                                                                                                                                                                            0.0s
     => CACHED [airmail stage-1 2/3] RUN yum -y install openssl && yum clean all                                                                                                                                                                                                                                 0.0s
     => CACHED [airmail build  2/11] RUN apt update && apt install -y libssl-dev clang pkg-config                                                                                                                                                                                                                0.0s
     => CACHED [airmail build  3/11] WORKDIR /usr/src/airmail                                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  4/11] COPY ./airmail ./airmail                                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  5/11] COPY ./airmail_indexer ./airmail_indexer                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  6/11] COPY ./airmail_service ./airmail_service                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  7/11] COPY ./Cargo.toml ./Cargo.toml                                                                                                                                                                                                                                              0.0s
     => CACHED [airmail build  8/11] COPY ./Cargo.lock ./Cargo.lock                                                                                                                                                                                                                                              0.0s
     => CACHED [airmail build  9/11] RUN cargo install --path ./airmail_service                                                                                                                                                                                                                                  0.0s
     => CACHED [airmail build 10/11] WORKDIR /app                                                                                                                                                                                                                                                                0.0s
     => CACHED [airmail build 11/11] RUN rm -rf /usr/src/airmail                                                                                                                                                                                                                                                 0.0s
     => CACHED [airmail stage-1 3/3] COPY --from=build /usr/local/cargo/bin/airmail_service /usr/local/bin/airmail_service                                                                                                                                                                                       0.0s
     => [airmail] exporting to image                                                                                                                                                                                                                                                                             0.0s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:4d542d5eb78d8881b10415843d04380d7f8e1c5a29bd2d1a8bdd9912ed014da6                                                                                                                                                                                                                 0.0s
     => => naming to docker.io/library/airmail:latest                                                                                                                                                                                                                                                            0.0s
    root@k8s-eu-1-worker-4:~/airmail# 


Building the index from the pbf file   -> error message : **error returned from database: (code: 14) unable to open database file**

root@k8s-eu-1-worker-4:~/airmail# docker compose run indexer \
> indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db \
> --index /data/index/ \
> load-osm-pbf /data/australia-oceania-latest.osm.pbf
Error: error returned from database: (code: 14) unable to open database file

Caused by:
    (code: 14) unable to open database file

**Comment by ellenhp** [comment]
Did you follow step 2 in the readme?

> 2. Download Who's On First (SpatiaLite format). For planet see: https://geocode.earth/data/whosonfirst/combined/ and https://data.geocode.earth/wof/dist/spatial/whosonfirst-data-admin-latest.spatial.db.bz2

After downloading it, go double-check [the comment here](https://github.com/ellenhp/airmail/issues/27#issuecomment-2331999759) and make sure you have the correct filename set for the WhosOnFirst database in the docker-compose.yaml file.

**Comment by raphael10-collab** [comment]
Hi @ellenhp 

with this data folder content : 

    root@k8s-eu-1-worker-4:~/airmail# ls -lah ./data/
    total 729M
    drwxr-xr-x 2 root root 4.0K Sep  5 18:25 .
    drwxr-xr-x 9 root root 4.0K Sep  5 18:26 ..
    -rw-r--r-- 1 root root 729M Sep  3 01:23 australia-latest.osm.pbf // file downloaded from here: https://download.geofabrik.de/australia-oceania/australia-latest.osm.pbf


with this docker-composer.yaml file : 

    root@k8s-eu-1-worker-4:~/airmail# cat docker-compose.yaml 
    name: airmail
    
    services:
      osmx:
        image: osmx:latest
        build:
          context: airmail_indexer
          dockerfile: ./Dockerfile.osmx
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: expand /data/australia-latest.osm.pbf /data/australia-latest.osm.osmx  // <-------------------------------
    
      indexer:
        image: indexer:latest
        build:
          context: ./
          dockerfile: ./airmail_indexer/Dockerfile
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db --index /data/index/ --admin-cache /data/admin-cache load-osm-pbf /data/australia-latest.osm.pbf    // <-----------------------------------------------
    
      airmail:
        image: airmail:latest
        build:
          context: ./
          dockerfile: ./Dockerfile
        environment:
          AIRMAIL_BIND: "0.0.0.0:3000"
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        ports:
          - 3000:3000
        command: --index /data/index/


I built the images : 

    root@k8s-eu-1-worker-4:~/airmail# docker compose build
    [+] Building 9.2s (48/48) FINISHED                                                                                                                                                                                                                                                                 docker:default
     => [indexer internal] load .dockerignore                                                                                                                                                                                                                                                                    0.1s
     => => transferring context: 96B                                                                                                                                                                                                                                                                             0.0s
     => [indexer internal] load build definition from Dockerfile                                                                                                                                                                                                                                                 0.0s
     => => transferring dockerfile: 464B                                                                                                                                                                                                                                                                         0.0s
     => [airmail internal] load metadata for docker.io/library/rust:1.76                                                                                                                                                                                                                                         7.0s
     => [osmx internal] load build definition from Dockerfile.osmx                                                                                                                                                                                                                                               0.1s
     => => transferring dockerfile: 788B                                                                                                                                                                                                                                                                         0.0s
     => [osmx internal] load .dockerignore                                                                                                                                                                                                                                                                       0.1s
     => => transferring context: 2B                                                                                                                                                                                                                                                                              0.0s
     => [osmx internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                                                                                                                         6.5s
     => [airmail internal] load build definition from Dockerfile                                                                                                                                                                                                                                                 0.2s
     => => transferring dockerfile: 600B                                                                                                                                                                                                                                                                         0.1s
     => [airmail internal] load .dockerignore                                                                                                                                                                                                                                                                    0.3s
     => => transferring context: 96B                                                                                                                                                                                                                                                                             0.0s
     => [airmail internal] load metadata for docker.io/library/fedora:39                                                                                                                                                                                                                                         5.8s
     => [osmx builder 1/8] FROM docker.io/library/ubuntu:20.04@sha256:fa17826afb526a9fc7250e0fbcbfd18d03fe7a54849472f86879d8bf562c629e                                                                                                                                                                           0.0s
     => CACHED [osmx stage-1 2/4] RUN apt-get update && apt-get install -y     libexpat1     libssl1.1   && rm -rf /var/lib/apt/lists/*                                                                                                                                                                          0.0s
     => CACHED [osmx builder 2/8] RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get install -y     cmake     clang     libbz2-dev     libz-dev     libexpat-dev     libssl-dev     git   && rm -rf /var/lib/apt/lists/*                                                                    0.0s
     => CACHED [osmx builder 3/8] WORKDIR /usr/src/                                                                                                                                                                                                                                                              0.0s
     => CACHED [osmx builder 4/8] RUN git clone --recurse-submodules https://github.com/protomaps/OSMExpress.git                                                                                                                                                                                                 0.0s
     => CACHED [osmx builder 5/8] WORKDIR /usr/src/OSMExpress                                                                                                                                                                                                                                                    0.0s
     => CACHED [osmx builder 6/8] RUN git checkout 24cdc6cca55f45b4019e2d490c2321c366ca3362                                                                                                                                                                                                                      0.0s
     => CACHED [osmx builder 7/8] RUN cmake -DCMAKE_BUILD_TYPE=Release .                                                                                                                                                                                                                                         0.0s
     => CACHED [osmx builder 8/8] RUN make -j$(nproc)                                                                                                                                                                                                                                                            0.0s
     => CACHED [osmx stage-1 3/4] COPY --from=builder /usr/src/OSMExpress/osmx /usr/local/bin/osmx                                                                                                                                                                                                               0.0s
     => CACHED [osmx stage-1 4/4] WORKDIR /var/osm                                                                                                                                                                                                                                                               0.0s
     => [osmx] exporting to image                                                                                                                                                                                                                                                                                0.2s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:c0f9596ad434039d629b7f078723ffa0ab352c0653635ac59e8b1a23dc7c3f0a                                                                                                                                                                                                                 0.0s
     => => naming to docker.io/library/osmx:latest                                                                                                                                                                                                                                                               0.1s
     => [airmail stage-1 1/3] FROM docker.io/library/fedora:39@sha256:86ba29d15976848f8b9f27d533156d6e43553678d0832bb8ebc95ff6c2331be6                                                                                                                                                                           0.0s
     => [indexer build  1/11] FROM docker.io/library/rust:1.76@sha256:d36f9d8a9a4c76da74c8d983d0d4cb146dd2d19bb9bd60b704cdcf70ef868d3a                                                                                                                                                                           0.0s
     => [airmail internal] load build context                                                                                                                                                                                                                                                                    1.1s
     => => transferring context: 979.21kB                                                                                                                                                                                                                                                                        1.0s
     => [indexer internal] load build context                                                                                                                                                                                                                                                                    1.0s
     => => transferring context: 979.21kB                                                                                                                                                                                                                                                                        0.9s
     => CACHED [indexer  2/10] RUN apt-get update && apt-get install -y libssl-dev capnproto clang pkg-config libzstd-dev libsqlite3-mod-spatialite && rm -rf /var/lib/apt/lists/*                                                                                                                               0.0s
     => CACHED [indexer  3/10] WORKDIR /usr/src/airmail                                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  4/10] COPY ./airmail ./airmail                                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  5/10] COPY ./airmail_indexer ./airmail_indexer                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  6/10] COPY ./airmail_service ./airmail_service                                                                                                                                                                                                                                          0.0s
     => CACHED [indexer  7/10] COPY ./Cargo.toml ./Cargo.toml                                                                                                                                                                                                                                                    0.0s
     => CACHED [indexer  8/10] COPY ./Cargo.lock ./Cargo.lock                                                                                                                                                                                                                                                    0.0s
     => CACHED [indexer  9/10] RUN cargo install --path ./airmail_indexer                                                                                                                                                                                                                                        0.0s
     => CACHED [indexer 10/10] WORKDIR /var/airmail                                                                                                                                                                                                                                                              0.0s
     => CACHED [airmail stage-1 2/3] RUN yum -y install openssl && yum clean all                                                                                                                                                                                                                                 0.0s
     => CACHED [airmail build  2/11] RUN apt update && apt install -y libssl-dev clang pkg-config                                                                                                                                                                                                                0.0s
     => CACHED [airmail build  3/11] WORKDIR /usr/src/airmail                                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  4/11] COPY ./airmail ./airmail                                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  5/11] COPY ./airmail_indexer ./airmail_indexer                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  6/11] COPY ./airmail_service ./airmail_service                                                                                                                                                                                                                                    0.0s
     => CACHED [airmail build  7/11] COPY ./Cargo.toml ./Cargo.toml                                                                                                                                                                                                                                              0.0s
     => CACHED [airmail build  8/11] COPY ./Cargo.lock ./Cargo.lock                                                                                                                                                                                                                                              0.0s
     => CACHED [airmail build  9/11] RUN cargo install --path ./airmail_service                                                                                                                                                                                                                                  0.0s
     => CACHED [airmail build 10/11] WORKDIR /app                                                                                                                                                                                                                                                                0.0s
     => CACHED [airmail build 11/11] RUN rm -rf /usr/src/airmail                                                                                                                                                                                                                                                 0.0s
     => CACHED [airmail stage-1 3/3] COPY --from=build /usr/local/cargo/bin/airmail_service /usr/local/bin/airmail_service                                                                                                                                                                                       0.0s
     => [indexer] exporting to image                                                                                                                                                                                                                                                                             0.2s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:0b6cda1f7402eed2ab9f920235ab2ea8f53861eca7a7b7e38f5c17fae0600b3c                                                                                                                                                                                                                 0.2s
     => => naming to docker.io/library/indexer:latest                                                                                                                                                                                                                                                            0.0s
     => [airmail] exporting to image                                                                                                                                                                                                                                                                             0.2s
     => => exporting layers                                                                                                                                                                                                                                                                                      0.0s
     => => writing image sha256:4d542d5eb78d8881b10415843d04380d7f8e1c5a29bd2d1a8bdd9912ed014da6                                                                                                                                                                                                                 0.1s
     => => naming to docker.io/library/airmail:latest                                                                                                                                                                                                                                                            0.1s
    root@k8s-eu-1-worker-4:~/airmail# 


And, then, tried to build the index, but got again **error returned from database: (code: 14) unable to open database file**  : 

    root@k8s-eu-1-worker-4:~/airmail# docker compose run indexer \
    > indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db \
    > --index /data/index/ \
    > load-osm-pbf ./data/australia-latest.osm.pbf 
    [2024-09-05T16:31:41Z INFO  tantivy::indexer::segment_updater] save metas
    Error: error returned from database: (code: 14) unable to open database file
    
    Caused by:
        (code: 14) unable to open database file

**Comment by ellenhp** [comment]
"the database file" in this error message is the WhosOnFirst database file that I've mentioned in the two previous comments. This is different from the OpenStreetMap file (osm.pbf). Based on the output of your `ls` command, it appears you're missing the WhosOnFirst database file, so it makes sense to me that you are getting this error. Please download the WhosOnFirst database file and try again, making sure it is named correctly.

**Comment by ellenhp** [comment]
This is what my data directory looks like.

``` $ ls -l ~/src/airmail/data
total 117201040
-rw-r--r--. 1 ellen ellen   757904031 Aug  6 12:37 australia-latest.osm.pbf
drwxr-xr-x. 1 ellen ellen         572 Aug 16 17:43 index
-rw-r--r--. 1 ellen ellen 80954555269 Jun  9 18:04 planet-240603.osm.pbf
-rw-r--r--. 1 ellen ellen 38301368320 Aug  6 12:54 whosonfirst-data-admin-latest.spatial.db
```

The file **`whosonfirst-data-admin-latest.spatial.db`** is necessary for indexing to work, otherwise you'll get the error you described.

**Comment by raphael10-collab** [comment]
@ellenhp This time the decompressed database file is present, but I get this error message:

"**error returned from database: (code: 14) unable to open database file**"   : 

**data** folder : 

    root@k8s-eu-1-worker-4:~/airmail/data# ls -lah
    total 116G
    drwxr-xr-x 2 root root 4.0K Sep  5 20:34 .
    drwxr-xr-x 9 root root 4.0K Sep  5 18:43 ..
    -rw-r--r-- 1 root root  80G Sep  5 03:00 planet.osm.pbf
    -rw-r--r-- 1 root root  36G Aug 22 11:22 whosonfirst-data-admin-latest.spatial.db

modified **docker-compose.yaml** file : 

    root@k8s-eu-1-worker-4:~/airmail# cat docker-compose.yaml 
    name: airmail
    
    services:
      osmx:
        image: osmx:latest
        build:
          context: airmail_indexer
          dockerfile: ./Dockerfile.osmx
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: expand /data/planet.osm.pbf /data/planet.osm.osmx  // <---------------------------
    
      indexer:
        image: indexer:latest
        build:
          context: ./
          dockerfile: ./airmail_indexer/Dockerfile
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        command: indexer --wof-db /data/whosonfirst-data-admin-latest.spatial.db --index /data/index/ --admin-cache /data/admin-cache load-osm-pbf /data/planet.osm.pbf  // <----------------------------
    
      airmail:
        image: airmail:latest
        build:
          context: ./
          dockerfile: ./Dockerfile
        environment:
          AIRMAIL_BIND: "0.0.0.0:3000"
        stop_signal: KILL
        restart: "no"
        volumes:
          - ./data:/data:z
        ports:
          - 3000:3000
        command: --index /data/index/



    root@k8s-eu-1-worker-4:~/airmail# docker compose run indexer \
    > indexer --wof-db ./data/whosonfirst-data-admin-latest.spatial.db \
    > --index /data/index/ \
    > load-osm-pbf ./data/planet.osm.pbf 
    Error: error returned from database: (code: 14) unable to open database file
    
    Caused by:
        (code: 14) unable to open database file
    root@k8s-eu-1-worker-4:~/airmail# 

what am I missing or doing wrong?

**Comment by ellenhp** [comment]
Try using absolute paths with docker. Because of the way the bind mounds work, an absolute path is required. `/data/whosonfirst-data-admin-latest.spatial.db`  instead of `./data/whosonfirst-data-admin-latest.spatial.db`.

**Comment by raphael10-collab** [comment]
@ellenhp already tried in both ways: first with absolute path /data/whosonfirst-data-admin-latest.spatial.db and then ./data/whosonfirst-data-admin-latest.spatial.db and in both cases : "Error: error returned from database: (code: 14) unable to open database file" . 

Now it's running target/debug/indexer : 

    root@k8s-eu-1-worker-4:~/airmail# cargo run --bin indexer -- \
    > --wof-db ./data/whosonfirst-data-admin-latest.spatial.db \
    > --index /data/index/ \
    > load-osm-pbf ./data/planet.osm.pbf
        Finished dev [unoptimized + debuginfo] target(s) in 0.93s
         Running `target/debug/indexer --wof-db ./data/whosonfirst-data-admin-latest.spatial.db --index /data/index/ load-osm-pbf ./data/planet.osm.pbf`
    [2024-09-05T19:07:20Z INFO  indexer::osm_pbf] Generating OSM node map from: ./data/planet.osm.pbf

I guess it will take a while

**Comment by ellenhp** [comment]
There may be something I'm missing that's causing docker-compose to fail but this has worked for a few users now. I'm glad it's working with Cargo at least. The planet import takes about 12 hours on my Ryzen 5900X machine with NVMe disks. I noticed it seems like you may be running this on kubernetes (or directly on a node?). If so, depending on the machine specifications, it may be faster to run the build locally and then upload the files. My demo deployment uses a CephFS RWX volume shared among all serving pods. I run the indexing process on my workstation, then upload the index to that RWX volume and switch the deployment to point to the new index.

**Comment by raphael10-collab** [comment]
I'm running the cargo run indexer directly on a node. May be, once finished, I will upload the built files on a volume, and may be, shared among serving pods. 
One step at a time.

I will see tomorrow the result

**Comment by ellenhp** [comment]
Going to close this as the issue seems to have been resolved. Feel free to open another issue if you encounter more difficulties.

**Comment by raphael10-collab** [comment]
Hi Ellen,

it's stil running : 
![image](https://github.com/user-attachments/assets/d5b8844e-add1-468c-ad3b-c710cbb565c7)
